### ISSUE TITLE
屏幕抖动问题

### ISSUE THREAD

**Issue by Pathsis** [Lonor/site#160]
具体表现是：
1. 在桌面视图下，在出现和不出现垂直滚动条的不同网页之间切换会出现网页抖动，例如，在`/blog`和`/tags`之间切换不会抖动，但在`/`和上述页面之间切换会抖动；
3. 在桌面试图下，搜索时一定会出现屏幕抖动。

https://user-images.githubusercontent.com/72077265/227714510-14f26c96-ac7a-4abf-9dba-ca6e8fc04bc1.mp4

**Comment by Lonor** [comment]
看样子是子页面内部的样式把 Layout 撑开了... 我这边没能复现...

**Comment by Pathsis** [comment]
> 看样子是子页面内部的样式把 Layout 撑开了... 我这边没能复现...

我在global.css中加入了入overflow-y-scroll，避免了这个问题：

```css
@layer base {
  body {
    @apply my-8 mx-auto max-w-3xl md:overflow-y-scroll;
    font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial,"Noto Sans", sans-serif, "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
  }
```
